'use strict';

module.exports = {
  DEFAULT_NUMBER_OF_DECIMAL_PLACE: 2,
  DEFAULT_NUMBER_OF_DIGITS_IN_NUMBER: 6,
  DEFAULT_NUMBER_OF_DIGITS_IN_PHONE: 10,
  DEFAULT_NUMBER_OF_WORDS_IN_PHRASE: 12,
  DEFAULT_MIN_NUMBER_INTEGER: -2147483647,
  DEFAULT_MAX_NUMBER_INTEGER: 2147483647,
  TIME_FIXED_EPOCH: 1604161316,
  TIME_FIXED_UTC_TIMESTAMP: '2022-01-01T01:23:21.281Z',
  TIME_ZEROTH_EPOCH: 0,
  TIME_ZEROTH_EPOCH_UTC_TIMESTAMP: '1970-01-01T00:00:00.000Z',
  DAY_SHORT_NAME: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
  DAY_FULL_NAME: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
  MONTH_SHORT_NAME: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec'
  ],
  MONTH_FULL_NAME: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ],
  NUMERIC_DIGITS: '0123456789',
  HEX_CHARACTERS_LOWER_CASE: '0123456789abcdef',
  MD_HASH_LENGTH: 32,
  SHA1_HASH_LENGTH: 40,
  SHA224_HASH_LENGTH: 56,
  SHA256_HASH_LENGTH: 64,
  SHA384_HASH_LENGTH: 96,
  SHA512_HASH_LENGTH: 128
};
