export default [
  'Altitude Plaza',
  'Apollo Apartment',
  'Blue Apartment',
  'Broadway Plaza',
  'Central Park Apartment',
  'Century Tower',
  'Crown Tower',
  'Crystal Plaza',
  'Darling Building',
  'East Side Living',
  'Edge Apartment',
  'Four Flamingo Plaza',
  'Garden Apartment',
  'Gold Star Plaza',
  'Green Lake View',
  'Green Tower',
  'Green Villa',
  'Greenway Apartment',
  'Greenway Court Plaza',
  'Hillside Apartment',
  'Kingsford Plaza',
  'La Casa Apartment',
  'La Grande Apartment',
  'Lake View Apartment',
  'Lakeside Apartment',
  'Lakeside View Apartment',
  'Lilly Apartment',
  'Luxury Lake View',
  'Millennium Park Apartment',
  'Oak Plaza',
  'Paradise Palms',
  'Park Place',
  'Park Ridge Plaza',
  'Parkview Living',
  'Regal Apartment',
  'River View Apartment',
  'Rose Apartment',
  'Royal View Plaza',
  'Seaview Apartment',
  'Skyline Plaza',
  'Stanley Park',
  'Sunrise Apartment',
  'Sunset Apartment',
  'Sunshine Palace',
  'Surf Rider Apartment',
  'The Brooklyn Plaza',
  'The Luxury Palace',
  'The Nirvana Palace',
  'The Palm',
  'The Pinetree Palace',
  'The River Side',
  'The Star Tower',
  'The View',
  'Timber Ridge Apartment',
  'Town Apartment',
  'Town Square Apartment',
  'Village Villas'
];